### ISSUE TITLE
Getting Uncaught SyntaxError: Unexpected token 'export' (at autocomplete.min.js:1:8891)

### ISSUE THREAD

**Issue by jaimefuhr** [lekoala/bootstrap5-autocomplete#9]
Tried the latest and one version back.  Getting these two errors with the latest version:

Uncaught SyntaxError: Unexpected token 'export' (at autocomplete.js:1:880).   

line 880:  export default Autocomplete;

My code:

Autocomplete.init("input.autocomplete", {
                liveServer: "/services/CustomerLookup.ashx",
                suggestionsThreshold:  3,
                valueField: "value",
                labelField: "label",
                highlightTyped: true,
                onSelectItem: console.log
            });

**Comment by jaimefuhr** [comment]
I forgot to include type="module" to the script reference.   

<script type="module" src="../includes/vendor/bootstrap5-autocomplete-master/autocomplete.js"></script>
